### ISSUE TITLE
我毕设也想做个金融类app

### ISSUE THREAD

**Issue by OrangeSnow** [jingjingke/vuePro-demo#5]
现在3月了，毕设还没有很大的着落，真是一个头两个大，大佬能不能向你请教一下，我QQ2847267227

**Comment by jingjingke** [comment]
我也不知道怎么能帮到你，如果对demo有啥不懂的地方可以加我QQ：919948650

**Comment by OrangeSnow** [comment]
谢谢大佬，我差不多自己能解决了

**Comment by OrangeSnow** [comment]
人被逼一逼，还是有潜力的
